# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 816c4d3d94b309ef630ad4b03b40ef959f19792fa3fa6e571f3b9fb67c4253d3adc7bf10fa6ce3458400149437720fd8dd4b74b120a3f54edf77f2f431e93520

test:
  secret_key_base: 446ff41652738b47f399f15d0af7b8035eab7e64b2b41721a014a685c89a7489f93adbeb6c6ebfa42476f89c3d6261e4a180ff2cd83fccb939f6ddbd5379aec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
